
# my project folder is like this, a payroll folder that contains three sub folders, backend folder that contains(employes app folder that houses apps.py, viewsets.py, serializers.py, views.py, tempaltetags, urls.py e.t.c, payroll_system folder that has settings.py, asgi.py, urls.py, wsgi.py, e.t.c, payroll-env folder, static folder, template folder, manage.py file, package.json), frontend has all the react folders(build, node_modules, public, src, e.t.c), and the third folder is the media folder, then in the root I have .env, .gitgnore, Procfile, requirements.txt, pay.db..I want  to deploy to render, so that both my react and django will have one web addrees..also I want to use docker for deployments, guide me on how to use it to deploy on brimble..






































# my project folder is like this, a payroll folder that contains three sub folders, backend folder that contains(employes app folder that houses apps.py, viewsets.py, serializers.py, views.py, tempaltetags, urls.py e.t.c, payroll_system folder that has settings.py, asgi.py, urls.py, wsgi.py, e.t.c, payroll-env folder, static folder, template folder, manage.py file, package.json), frontend has all the react folders(build, node_modules, public, src, e.t.c), and the third folder is the media folder, then in the root I have .env, .gitgnore, Procfile, requirements.txt, pay.db..I want  to deploy to render, so that both my react and django will have one web addrees..also I want to use docker for deployments, guide me on how to use it to deploy on brimble..








