from rest_framework.routers import DefaultRouter
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from . import views
from . import generate_pdf
from .viewsets import *


router = DefaultRouter()
router.register('register', RegisterViewSet, basename='register')
router.register('hr_register', HrManagerRegisterViewSet,
                basename='register_hr')
router.register('create/profile', ProfileViewSet,
                basename='create_profile')
router.register('view/profile', ViewProfileViewSet, basename='view_profile')
router.register('company/profile', CreateCompanyProfile,
                basename='company_profile')
router.register('view/profiles', ViewAllProfilesViewSet,
                basename='view_profiles')
router.register('create/fingerprint', CreateWebAuthnCredentialViewSet,
                basename='create_fingerprint')
router.register('edit/profile', EditProfileViewSet, basename='edit_profile')
router.register('employee_register', EmployeeRegisterViewSet,
                basename='register_employee')
router.register('manager_register', ManagerRegisterViewSet,
                basename='register_manager')
router.register('overallAdmin_register', OverallAdminRegisterViewSet,
                basename='register_overallAdmin')
router.register('login', LoginViewSet, basename='login')
router.register('users', UserViewSet, basename='users')

urlpatterns = [
    path('', views.index, name='index'),
    path('api/my/profile/', MyProfileView.as_view()),
    path('view/messages/', views.view_messages, name='view_messages'),
    path('my-tax/', views.my_tax_deduction_view, name='my_tax'),
    path('all-tax/', views.all_tax_deductions_view, name='all_tax'),
    path('team/review', views.team_review_list_view, name='team-review-list'),
    path('create/team/review', views.team_review_create_view, name='team-review-create'),
    path('monthly/', views.monthy_attendance, name='monthly_attendance'),
    path('unread-messages/', views.unread_message_count,
         name='unread_message_count'),
    path('send-message/<int:user_id>/', views.send_message, name='send_message'),
    path('inbox/', views.inbox, name='inbox'),
    path('message/<int:message_id>/', views.message_detail, name='message_detail'),
    path('manager/employees', views.manager_team_view, name='manager_team_view'),
    path('hr/employees/', views.hr_employee_list,
         name='hr_employee_list'),
    path('hr/employees/<int:pk>/', views.employee_profile_detail,
         name='employee_profile_detail'),
    path('tasks', views.task_list, name='task_list'),
    path('tasks/create', views.TaskCreate.as_view(), name='task_create'),
    #     path('tasks/create', views.task_create, name='task_create'),
    path('tasks/review/<int:task_id>/', views.task_review, name='task_review'),
    path('Ontech/dashboard', views.dashboard, name='ontech_dashboard'),
    path('attendance/', AttendanceView.as_view(), name='attendance'),
    path('attendance/check-method/', check_method),
    path('generate-salary-slip/<int:employee_id>/',
         generate_pdf.generate_salary_slip, name='generate_salary_slip'),
    path('generate/bulk/salary/slips/', generate_pdf.generate_salary_slips_bulk,
         name='generate_salary_slips_bulk'),
    path('api/logout/', CustomLogoutView.as_view(), name='knox_logout'),
    path("logout/", logout_view, name="logout"),
    path('notifications/unread-count/', views.get_unread_notification_count,
         name='unread_notification_count'),
    path('notifications/mark-read/', views.mark_notification_read,
         name='mark_notification_read'),
    path('notifications/', views.notifications_list, name='notifications_list'),
    path('notifications/read/<int:notification_id>/',
         views.read_notification, name='read_notification'),
    path('api/attendance/biometric/status/', BiometricAttendanceStatusView.as_view(),
         name='biometric_status'),
    path('api/attendance/biometric/status/', BiometricAttendanceStatusView.as_view(),
         name='biometric_status'),
    path('create/review', views.create_review, name='create_reviews'),
    path('get/reviews', views.get_performance_reviews,
         name='get_performance_reviews'),
    path('complaints/', views.complaint_list, name='complaint_list'),
    path('create/complaints/', views.create_complaint, name='create_complaint'),
    path('complaints/<int:pk>/respond/',
         views.respond_to_complaint_view, name='respond_complaint'),
    path('complaints/<int:pk>/reply/',
         views.reply_to_complaint_view, name='reply_complaint'),
    path('update/leave/balance/<int:employee_id>/',
         views.update_leave_balance, name='update_leave_balance'),
    path('view/leave/balance/', views.view_leave_balances,
         name="view_leave_balances"),
    path('employees', views.user_list_view, name='user_list'),
    path('employees/<int:user_id>/',
         views.user_profile_view, name='user_profile'),
    path('create-deduction/<int:employee_id>/',
         views.create_tax_deduction, name='create_tax_deduction'),
    path('tax/deductions/', views.view_tax_deductions,
         name='view_tax_deductions'),
    path('get/tax/deductions/', views.get_tax_deductions,
         name='get_tax_deductions'),
    path('create/profile', CreateProfileAPIView.as_view(), name='create_profile'),
    path("api/csrf/", GetCRSFToken.as_view()),
#     path('api/csrf/', get_csrf_token, name='get-csrf-token'),
    path('payroll/login_view/', login_view, name='login_view'),
    path('payroll/logout_view/', logout_view, name='logout_view'),
    path('payroll/whoami/', whoami, name='whoami'),
    path('payroll/session/', session_view, name='session_view'),
    path("api/session-login/", SessionLoginView.as_view(), name="session_login"),
#     path("api/session-login/", SessionView.as_view(), name="session_login"),
    path('curent_user/', current_user, name='current_user'),
    path('api/fingerprint/request-options/',
         FingerprintRequestOptionsView.as_view(), name='fingerprint-request-options'),
    path('api/attendance/biometric/', BiometricAttendanceView.as_view(),
         name='biometric_attendance'),
    path('api/fingerprint/auth/', FingerprintAuthenticateView.as_view(),
         name='fingerprint-auth'),
    path('register/hr_manager/', views.hr_manager_register,
         name='hr_manager_register'),
    path('register/manager/', views.manager_register, name='manager_register'),
    path('register/overall_admin/', views.overall_admin_register,
         name='overall_admin_register'),
    path('register/employee/', views.employee_register, name='employee_register'),
    path('my/leave/requests/', views.my_leave_requests, name='my_leave_requests'),
     path('pending-leaves/', views.pending_leave_requests, name='pending_leave_requests'),
    path('leave/<int:leave_id>/approve/', views.approve_leave_request,
         name='approve_leave_request'),
    path('leave/<int:leave_id>/decline/', views.decline_leave_request,
         name='decline_leave_request'),
     path('leave-requests/', views.view_all_leave_requests, name='view_all_leave_requests'),
    path('create/leave/', views.create_leave_request,
         name='create_leave'),
    path('leave/delete/<int:leave_id>/',
         views.delete_leave_request, name='delete_leave_request'),
    path('leave/all/', views.all_leave_requests_admin,
         name='admin_all_leave_requests'),
    path('leave/department/', views.department_leave_requests,
         name='department_leave_requests'),
    path('salaries/', views.salary_list, name='salary_list'),
    path('salary/create/<int:user_id>/',
         views.create_salary, name='create_salary'),
    path('salary/edit/<int:salary_id>/',
         views.edit_salary, name='edit_salary'),
    path('salary/delete/<int:salary_id>/',
         views.delete_salary, name='delete_salary'),
    path('create_employee/<int:user_id>/',
         views.create_employee, name='create_employee'),
    path('salary/view/<int:salary_id>/',
         views.view_salary, name='view_salary'),
    path('employee/view/<int:employee_id>/',
         views.view_employee, name='view_employee'),
    path('employee_list/', views.employee_list, name='employee_list'),
    path('employee_records/', views.employee_record_list,
         name='employee_record_list'),
    path('employee_records/edit/<int:record_id>/',
         views.edit_employee_record, name='edit_employee_record'),
    path('employee_records/delete/<int:record_id>/',
         views.delete_employee_record, name='delete_employee_record'),
    path('emails/', EmailView.as_view(), name='email_form'),
    path('api/', include(router.urls)),
    path('', views.homepage, name='homepage'),
    path('', TemplateView.as_view(template_name='index.html'), name='homepage'),
    re_path(r'^.*$', views.frontend_view),

]
